Authorization
hseyyidkaplan/auth-app pull request #3
Opened 2021-09-12 12:21 UTC by MAkifUNLU

2021-09-12 12:23 UTC, MAkifUNLU commented
ShowEmail file commiti diğer branch de olması gerekiyordu.

2021-09-13 19:57 UTC, zeritte requested changes
degisiklikler gerekli, dondugunde bak lutfen

2021-09-13 19:57 UTC, zeritte commented on auth-app/src/components/ShowEmail.js
> +    writeEmail();
write degil de get diyelim fonksiyon ismine

2021-09-13 19:57 UTC, zeritte commented on auth-app/src/components/ShowEmail.js
> +  const [value, setValue] = useState("");
value degil email diye isimlendirelim

2021-09-13 19:57 UTC, zeritte commented on auth-app/src/components/ShowEmail.js
> +{/* <TouchableOpacity onPress={() => writeItemToStorage(Math.random().toString(36).substr(2, 5))}>
bunlari kaldir

2021-09-13 19:57 UTC, zeritte commented on auth-app/src/components/ShowEmail.js
> +{/* <TouchableOpacity onPress={() => writeItemToStorage(Math.random().toString(36).substr(2, 5))}>
yorumlarin hepsini

2021-09-13 19:57 UTC, zeritte commented on auth-app/src/screens/ProfileScreen.js
> +  const [setValue] = useState("");
buna hacet var mi?

2021-09-13 19:57 UTC, zeritte commented on auth-app/src/screens/ProfileScreen.js
> +    setValue(email);
buna da gerek yok, remove ettikten sonra niye kaydedesin

2021-09-13 19:57 UTC, zeritte commented on auth-app/src/screens/ProfileScreen.js
> + // const removeEmail = async () => {
yorumlari kaldiralim

2021-09-19 14:35 UTC, merged